### ISSUE TITLE
Add disclaimer for Terra repo (Fedora)

### ISSUE THREAD

**Issue by jn64** [PrismLauncher/prismlauncher.org#113]
Unlike the copr g3tchoo/prismlauncher which only contains PrismLauncher-related packages and presumably follows Fedora packaging guidelines, Terra is a third-party repo with other software that may or may not follow Fedora packaging guidelines... or any guidelines at all. [Their website](https://terra.fyralabs.com/) might as well be blank; the [only docs I could find](https://github.com/terrapkg/packages/blob/main/docs/BUILDING.md) were technical, not policy.

It may not be obvious to PrismLauncher/Fedora users since Terra is not widely known; they may think they are only adding a repo for PrismLauncher like a copr/PPA/OBS.

Also they appear to have [packages](https://repos.fyralabs.com/terra37/) that overlap with Fedora repos e.g. `dnf-plugins-core` which might result in unexpected behaviour for users (installing/upgrading to Terra packages instead of Fedora packages).

Personally I don't think Terra should be listed at all since there is a copr, but at least there should be a disclaimer about third-party repos and a link to the Terra website so users can inform themselves.

**Comment by jn64** [comment]
On a clean Fedora 37 toolbox image, adding the Terra repo *will* replace *dnf-plugins-core* and *python3-dnf-plugins-core*:

```shell
$ toolbox create --distro fedora --release 37 f37-terra-test
$ toolbox enter f37-terra-test
$ sudo dnf -y upgrade #upgrade everything from Fedora repos
$ sudo dnf config-manager --add-repo https://terra.fyralabs.com/terra.repo
$ sudo dnf --refresh check-update
dnf-plugins-core.noarch                                 1:4.3.1-1.fc37                            terra
python3-dnf-plugins-core.noarch                         1:4.3.1-1.fc37                            terra  
```

*python3-dnf-plugins-core* provides dnf commands like `config-manager` (used above to add a repo), `copr`, `download`, etc. In other words, terra can potentially alter the dnf commands responsible for adding/enabling/disabling repos.

**Even if there is no wrongdoing, I don't think this is a reasonable outcome for the average Fedora user that just wants to install PrismLauncher.**

**Comment by getchoo** [comment]
there was a discussion about this on discord, but for clarity i'll put my take on this here as well:

the repo itself is trustworthy from all the packages i've gone through, and the other contributors work hard to repackage previously unmaintained official packages, as well as some nice new ones. it is weird though for dnf-plugins-core to be replaced, and i'm not completely sure as to why it was. minus some epoch changes to make it work, the only difference between the official and terra package is [this](https://github.com/terrapkg/packages/blob/223c10828e53b609afa7db66986c9a2ffffdf00b/anda/dnf-plugins-core/0001-copr-Also-read-chroot-configs-from-config-files-in-c.patch) patch.

i'm not really sure why it's there since the bug it resolves seems to be a dead link - or at least i can't access with my basic red hat bugzilla account for some reason. looks like all it does is allow for reading chroot configs from a drop-in folder for copr.conf. i don't know what this is used for, but i'm guessing it's something to do with their custom build configs. maybe @lleyton could clear this up.

whatever the case is, i think a different solution would be better. you are completely right, this is weird behavior for a third party repo; and even if the changes aren't malicious in any way (which they aren't but still), something like `dnf-plugins-core` is pretty important and i think should stick to the main repos.

i'm not really sure about keeping it listed though, since on one hand it is a really good repo with quick updates and some nice packages but i could understand the confusion and maybe some frustration with users if prism is all they wanted and they end up getting packages from the official repositories replaced. unless the maintainers here have a different take on this, i think there should be a warning placed about it being a third party repo with more packages than just prism, as well as one about the current lack of documentation behind the policies, what gets included, how things are updated, etc until those are available.

**Comment by lleyton** [comment]
Heya! Just wanted to reiterate what I said on Discord about this:

Terra is a pretty new repository. As such, we're still getting a lot of the infrastructure around it set up, thus the website being barren. That specifically is being worked on, see the [dev branch](https://github.com/terrapkg/website/tree/dev).

As for the `dnf-plugins-core` package, it was pulled in when we migrated some packages from the old Ultramarine repos (an affiliated project, which used Koji at that time) to Terra. That is currently being dealt with, see https://github.com/terrapkg/packages/issues/37.

The documentation that was linked is outdated, but our bad for not removing that, see the [updated wiki](https://github.com/terrapkg/packages/wiki). Packaging guidelines are currently being worked on, and will be added to the wiki when complete :P

My personal suggestion would be adding a notice indicating that Terra is a 3rd-party repo. I would also like to note that the Terra repo is the upstream repository for the COPR's [nightly packages](https://copr.fedorainfracloud.org/coprs/g3tchoo/prismlauncher/package/prismlauncher-nightly/).

**Comment by jn64** [comment]
Thanks all. To be clear, I'm not accusing Terra of any wrongdoing. I'm also not asking for any changes on their part — they are free to patch dnf or anything else, have any policy, documentation, etc.

I'm solely asking from the point of view of PrismLauncher (maintainers, packagers, and users):

1. Is there a need to list 2 sources of the same packages for one distro?
2. Is there any benefit that Terra (or other 3rd-party distro) provides, that can't be addressed by Copr/Fedora infrastructure?
3. Is there any drawback to using Terra?

IMO, the answers are:

1. No. The downloads page is long enough, and listing 4 packages (nightly + qt5 variants) is already more confusing than most other apps. (This should be addressed separately.)
2. No for PrismLauncher maintainers or users. Maybe for packagers?
3. Yes (this issue)

Thus, I maintain that Terra should be removed from prismlauncher.org for now — and even if and when the conflicting packages are resolved, unless the answers to 1 and 2 become Yes.

> I would also like to note that the Terra repo is the upstream repository for the COPR's nightly packages.

This is more reason that PrismLauncher doesn't need to give users confusing and redundant options. Listing Copr alone is sufficient.

However this suggests an alternative solution, which is:

- Remove Terra section from prismlauncher.org
- Document on the Copr section of prismlauncher.org that the nightly packages are from Terra, with a link
- ~~Document on the Copr repo that the nightly packages are from Terra, with a link~~ (already done)

**Comment by getchoo** [comment]
these are really great points, and i honestly haven't thought about it in this way.

> To be clear, I'm not accusing Terra of any wrongdoing. I'm also not asking for any changes on their part — they are free to patch dnf or anything else, have any policy, documentation, etc.

of course! personally, i didn't get a hint of that of that, but it was a good idea to point these out since they are some genuine issues with the repository.

anyways, for the 3 questions:

> Is there a need to list 2 sources of the same packages for one distro?

i can agree here, i don't really see a need for this and i can see how it would create some confusion on top of the 4 packages. sections for other distributions also don't do this (besides *maybe* Ubuntu/Debian with the MPR and pacstall, but two of the subsections relate to the same repository and the other is for development builds so i don't think it's comparable).

> Is there any benefit that Terra (or other 3rd-party distro) provides, that can't be addressed by Copr/Fedora infrastructure?

from the point of view of someone that is *only* interested in Prism, not really. the only benefit currently would be faster updates for development builds since updates are checked for every 30 minutes and are built when a new commit is found. in contrast, my Copr repository is updated manually every 24 hours around midnight UTC (though this may change to match Terra at some point). due to the manual intervention needed though, these development build updates were inconsistent for a few days when i caught covid recently; so if a situation like that were to happen again (and i haven't automated the process), Terra would be more reliable.

outside of the aforementioned perspective, Terra does provide extra packages that are pretty popular (`starship` is an example off the top of my head) and could be useful for users. i see what you mean here though, Terra isn't immediately relevant to Prism like my Copr repository, and for simplicity's sake it could be better for Copr to be the only one listed.

> Is there any drawback to using Terra?

if/when `dnf-core-plugins` is removed and more documentation is added (which is underway), i don't see how there could be. it's still a great repository with a good selection of packages, ran by very dedicated and responsible team. even from the perspective of a Prism Launcher user, i don't see how it could hurt to add it unless you have concerns over the licensing of some packages or don't care about the other packages - which is understandable

> This is more reason that PrismLauncher doesn't need to give users confusing and redundant options. Listing Copr alone is sufficient.

> However this suggests an alternative solution, which is:
>  - Remove Terra section from prismlauncher.org
>  - Document on the Copr section of prismlauncher.org that the nightly packages are from Terra, with a link

overall, i can agree with this. the Copr repository is more relevant to Prism and would make the entire section simpler without hurting users of either repository. i like still giving the Fyra Labs/Terra team credit as well, since even though the spec file for the nightly builds are still maintained by [me](https://github.com/terrapkg/packages/commits/8a7038914863f9ac5ae249cc7a9573a223b23dac/anda/games/prismlauncher-nightly/prismlauncher-nightly.spec), the Terra updates workflow makes my life a lot easier - plus, one of the team members also [helped](https://pagure.io/prismlauncher-rpm/c/22367d6e2bed01e537bbb5d887fcef1c79bfb970?branch=main) in transitioning the spec file from PolyMC to Prism. Terra is a wonderful project, but i can understand why it might not be a great fit for it's own section.

i'll suggest changes in your PR to reflect this 👍🏻

**Comment by lleyton** [comment]
That sounds good to me!

As for Terra's policy, we try to avoid conflicts, so we'll be resolving those issues soon.
